# Generated by Django 6.0.6 on 2026-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Город'),
        ),
    ]
